#!/usr/bin/env node
// Deterministic generator for the AI-native docs structural regions.
//
// It rewrites ONLY the text between the explicit marker comments in
// docs/ai-native/*.md, so hand-written / agent-written prose outside the
// markers is never touched. No network, no LLM, Node built-ins only, so it
// is safe to run from a git hook on every commit.
//
// Markers (one section per pair):
//   <!-- ai-native:auto:START section=structure --> ... <!-- ai-native:auto:END -->
//   <!-- ai-native:auto:START section=history   --> ... <!-- ai-native:auto:END -->
//
// Design rules followed (see docs/ai-native/decision.md):
//  - idempotent: running twice yields identical bytes (sorted walk, fixed git range).
//  - cross-platform: path.sep handling, '\n' output, no shell globbing.
//  - bounded: capped tree depth, capped children per dir, capped git-log count.

import { execFileSync } from 'node:child_process';
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(SCRIPT_DIR, '..', '..');
const DOC_DIR = join(REPO_ROOT, 'docs', 'ai-native');

// --- bounds (coding-standards rule 1 & 8) ---
const MAX_DEPTH = 2; // top-level dirs + one level in
const MAX_CHILDREN = 40; // per directory, then an elision line
const GIT_LOG_COUNT = 40;
const GIT_TIMEOUT_MS = 15000;

// Generated / vendor directories pruned from the tree.
const EXCLUDE_DIRS = new Set([
  'node_modules', 'dist', 'dist-ssr', 'build', 'coverage',
  '.dart_tool', '.pub-cache', '.pub', '.gradle', 'Pods',
  '.next', 'out', '.turbo', '.vite', '.cache', '.parcel-cache',
  '.svelte-kit', '.output', '.venv', '__pycache__',
]);

// Known subsystems and their one-line purpose. A row is emitted only when the
// directory exists, so the map drops stale entries automatically.
const SUBSYSTEMS = [
  { path: 'src', label: 'Web frontend', purpose: 'React 18 + Vite + TypeScript UI (record/upload, MSAL auth, Supabase data).' },
  { path: 'workflow-server', label: 'Backend + MCP', purpose: 'Node HTTP backend: transcribe/summarize pipeline (AssemblyAI + Gemini); also hosts the MCP server, knowledge extraction, memory, and speaker-ID.' },
  { path: 'supabase', label: 'Data + edge', purpose: 'Postgres schema + migrations, RLS, and Deno edge functions (token exchange, audio URLs, profile generation, admin).' },
  { path: 'meeting-note-mobile', label: 'Mobile app', purpose: 'Flutter / Dart app (core / features / shared under app/lib).' },
  { path: 'product-page', label: 'Product page', purpose: 'Static product / marketing landing page.' },
  { path: 'scripts', label: 'Repo scripts', purpose: 'Root build, version-stamp, QA, and AI-native-docs helper scripts.' },
];

const MARK_START = (section) => `<!-- ai-native:auto:START section=${section} -->`;
const MARK_END = '<!-- ai-native:auto:END -->';
const AUTO_NOTE = '<!-- Generated by scripts/ai-native-docs/generate.mjs. Do not edit inside this region; run `npm run docs:ai-native`. -->';

/** Directories directly under `dir`, pruned and sorted. */
function childDirs(dir) {
  let entries;
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch (err) {
    // Unreadable directory: skip it rather than abort the whole tree.
    process.stderr.write(`ai-native-docs: cannot read ${dir}: ${err.message}\n`);
    return [];
  }
  return entries
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .filter((name) => !name.startsWith('.') && !EXCLUDE_DIRS.has(name))
    .sort((a, b) => a.toLowerCase().localeCompare(b.toLowerCase()));
}

/** Recursive, depth- and width-bounded directory tree as markdown lines. */
function walkTree(dir, prefix, depth, out) {
  if (depth > MAX_DEPTH) return;
  const names = childDirs(dir);
  const shown = names.slice(0, MAX_CHILDREN);
  shown.forEach((name, i) => {
    const last = i === shown.length - 1 && names.length <= MAX_CHILDREN;
    const branch = last ? '└── ' : '├── ';
    out.push(`${prefix}${branch}${name}/`);
    const nextPrefix = prefix + (last ? '    ' : '│   ');
    walkTree(join(dir, name), nextPrefix, depth + 1, out);
  });
  if (names.length > MAX_CHILDREN) {
    out.push(`${prefix}└── … (${names.length - MAX_CHILDREN} more)`);
  }
}

function buildStructureRegion() {
  const tree = ['.'];
  walkTree(REPO_ROOT, '', 1, tree);

  const rows = SUBSYSTEMS
    .filter((s) => existsDir(join(REPO_ROOT, s.path)))
    .map((s) => `| \`${s.path}/\` | ${s.label} | ${s.purpose} |`);

  const lines = [
    AUTO_NOTE,
    '',
    '### Repository structure',
    '',
    `Directories only, to depth ${MAX_DEPTH}; generated / vendor directories (node_modules, dist, build, coverage, .dart_tool, and similar) are pruned.`,
    '',
    '```text',
    ...tree,
    '```',
    '',
    '### Subsystem map',
    '',
    '| Path | Subsystem | Purpose |',
    '| --- | --- | --- |',
    ...rows,
  ];
  return lines.join('\n');
}

/** A directory exists and is readable. */
function existsDir(dir) {
  try {
    readdirSync(dir);
    return true;
  } catch {
    return false;
  }
}

/** Normalize em/en dashes out of reproduced git text (repo style: no em-dashes). */
function dedash(s) {
  return s.replace(/\s*[\u2014\u2013]\s*/g, ', ');
}

/** Recent commit subjects (newest first), bounded. Fails soft. */
function readGitSubjects(extraArgs) {
  try {
    const stdout = execFileSync(
      'git',
      ['log', `-n`, String(GIT_LOG_COUNT), '--pretty=format:%s', ...extraArgs],
      { cwd: REPO_ROOT, encoding: 'utf8', timeout: GIT_TIMEOUT_MS },
    );
    return stdout.split('\n').map((s) => dedash(s.trim())).filter(Boolean);
  } catch (err) {
    process.stderr.write(`ai-native-docs: git log failed: ${err.message}\n`);
    return null;
  }
}

const TYPE_BUCKETS = [
  { key: 'feat', title: 'Features' },
  { key: 'fix', title: 'Fixes' },
  { key: 'perf', title: 'Performance' },
  { key: 'eval', title: 'Evaluation' },
  { key: 'docs', title: 'Docs' },
  { key: 'other', title: 'Other' },
];

/** Classify "type(scope): subject" into a bucket key. */
function bucketOf(subject) {
  const m = /^([a-z]+)(\([^)]*\))?!?:/.exec(subject);
  const type = m ? m[1] : 'other';
  return TYPE_BUCKETS.some((b) => b.key === type) ? type : 'other';
}

function buildHistoryRegion() {
  const subjects = readGitSubjects(['--no-merges']);
  const merges = readGitSubjects(['--merges']);

  const lines = [
    AUTO_NOTE,
    '',
    '### Recent changes',
    '',
  ];

  if (subjects === null) {
    lines.push('_Git history unavailable when this file was generated._');
    return lines.join('\n');
  }

  lines.push(`Last ${subjects.length} non-merge commits, newest first, grouped by type.`);
  lines.push('');
  const grouped = new Map(TYPE_BUCKETS.map((b) => [b.key, []]));
  for (const s of subjects) grouped.get(bucketOf(s)).push(s);
  for (const b of TYPE_BUCKETS) {
    const items = grouped.get(b.key);
    if (items.length === 0) continue;
    lines.push(`**${b.title}**`);
    lines.push('');
    for (const s of items) lines.push(`- ${s}`);
    lines.push('');
  }

  if (merges && merges.length > 0) {
    lines.push('### Recent merges');
    lines.push('');
    for (const s of merges.slice(0, 10)) lines.push(`- ${s}`);
  }

  return lines.join('\n').replace(/\n+$/, '');
}

/** Replace the inner text of one marked region. Fails loud if markers missing. */
function replaceRegion(content, section, inner) {
  const start = MARK_START(section);
  const startIdx = content.indexOf(start);
  if (startIdx === -1) {
    throw new Error(`marker not found: ${start}`);
  }
  const afterStart = startIdx + start.length;
  const endIdx = content.indexOf(MARK_END, afterStart);
  if (endIdx === -1) {
    throw new Error(`closing marker not found after ${start}`);
  }
  const before = content.slice(0, afterStart);
  const after = content.slice(endIdx);
  return `${before}\n${inner}\n${after}`;
}

/** Rewrite one doc file's regions; return true if the bytes changed. */
function updateDoc(fileName, sections) {
  const filePath = join(DOC_DIR, fileName);
  let content;
  try {
    content = readFileSync(filePath, 'utf8');
  } catch (err) {
    throw new Error(`cannot read ${fileName}: ${err.message}`);
  }
  let next = content;
  for (const [section, inner] of Object.entries(sections)) {
    next = replaceRegion(next, section, inner);
  }
  if (next === content) return false;
  writeFileSync(filePath, next);
  return true;
}

function main() {
  const changed = [];
  if (updateDoc('intro.md', { structure: buildStructureRegion() })) changed.push('intro.md');
  if (updateDoc('history.md', { history: buildHistoryRegion() })) changed.push('history.md');

  if (changed.length === 0) {
    process.stdout.write('ai-native-docs: up to date.\n');
  } else {
    process.stdout.write(`ai-native-docs: regenerated ${changed.join(', ')}.\n`);
  }
}

try {
  main();
} catch (err) {
  // Surface clearly, but exit non-zero so a human run notices. The git hook
  // deliberately ignores this exit code so doc generation never blocks a commit.
  process.stderr.write(`ai-native-docs: ${err.message}\n`);
  process.exit(1);
}
