import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';
import type { TranscriptLanguage } from '../lib/transcriptSegments';

export type AppLanguage = 'en' | 'ko';

interface LanguageContextValue {
  appLanguage: AppLanguage;
  transcriptLanguage: TranscriptLanguage;
  setAppLanguage: (language: AppLanguage) => void;
  t: (key: TranslationKey) => string;
}

const LANGUAGE_STORAGE_KEY = 'meeting-note:app-language';

const LanguageContext = createContext<LanguageContextValue | null>(null);

const translations = {
  en: {
    accountSettings: 'Account Settings',
    accountSettingsSubtitle: 'Microsoft account details for your meeting notes workspace',
    account: 'Account',
    summaryPrompts: 'Summary prompts',
    speakerProfiles: 'Speaker Profiles',
    mcpSetup: 'MCP Setup',
    appLanguage: 'App language',
    appLanguageDescription: 'Controls app language, transcript display, and generated summary language.',
    english: 'English',
    korean: 'Korean',
    history: 'History',
    meetingNote: 'Meeting Note',
    meetingNotes: 'Meeting Notes',
    historySubtitle: 'Meeting notes you created across all chats',
    filterNotes: 'Filter',
    searchNotes: 'Search title, summary, owner, speaker, or tag',
    owner: 'Owner',
    allNotes: 'All notes',
    myNotes: 'My notes',
    sharedWithMeNotes: 'Shared with me',
    sort: 'Sort',
    meetingNewest: 'Meeting date, newest',
    meetingOldest: 'Meeting date, oldest',
    createdNewest: 'Created date, newest',
    createdOldest: 'Created date, oldest',
    titleAZ: 'Title A-Z',
    titleZA: 'Title Z-A',
    uploadAudioSubtitle: 'Upload or record audio, then generate a meeting summary',
    uploadAudioFile: 'Upload Audio File',
    uploading: 'Uploading',
    regenerateSummary: 'Regenerate Summary',
    forwardSummary: 'Forward Summary',
    projectNotes: 'Project Notes',
    addToProject: 'Add to Project',
    alreadyInProject: 'Already in project',
    noProjectsFound: 'No projects found.',
    removeFromProject: 'Remove from Project',
    copied: 'Copied',
    saved: 'Saved',
    sending: 'Sending...',
    sent: 'Sent!',
    delete: 'Delete',
    deleteNote: 'Delete Note',
    deleteProject: 'Delete project',
    deletePrompt: 'Delete prompt',
    deleteSavedSpeaker: 'Delete saved speaker?',
    create: 'Create',
    createProject: 'Create Project',
    projectName: 'Project name',
    noteNameRequired: 'Note name is required.',
    projectNameRequired: 'Project name is required.',
    saveProfile: 'Save Profile',
    editProfile: 'Edit profile',
    profileSaved: 'Profile saved.',
    saveAll: 'Save All',
    saveAllProfiles: 'Save all profiles?',
    confirmSaveAll: 'Confirm Save All',
    discardSummary: 'Discard Summary',
    adminWorkspace: 'Admin workspace',
    adminAccessRequired: 'Admin access required',
    transcriptionControls: 'Transcription Controls',
    summaryControls: 'Summary Controls',
    globalSummaryContext: 'Global summary context',
    settingsSaved: 'Settings saved.',
    transcriptionSettingsSaved: 'Transcription settings saved.',
    loadingAccount: 'Loading account...',
    loadingSpeakerData: 'Loading speaker data...',
    noSavedSpeakerMatched: 'No saved speaker matched your Microsoft name. Names in transcripts are compared after normalizing punctuation and alternate-script parentheses. Label yourself in a transcript or add a matching saved speaker.',
    savedSpeakersDescription: 'Saved speakers on your account, excluding the profile matched to your Microsoft name on the Account tab.',
    useEditProfileHint: 'Use Edit profile to add structured speaker context for better summaries.',
    list: 'List',
    calendar: 'Calendar',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    summary: 'Summary',
    transcription: 'Transcription',
    copy: 'Copy',
    edit: 'Edit',
    done: 'Done',
    save: 'Save',
    cancel: 'Cancel',
    editTranscriptSegment: 'Edit transcript segment',
    failedSaveSegmentEdit: 'Failed to save transcript segment edit',
    discard: 'Discard',
    uploadAudio: 'Upload Audio',
    recentRecordings: 'Recent Recordings',
    summarize: 'Summarize',
    project: 'Project',
    projects: 'Projects',
    newProject: 'New Project',
    adminControls: 'Admin Controls',
    adminAnalytics: 'Admin Analytics',
    share: 'Share',
    close: 'Close',
    syncProfile: 'Sync Profile',
    renameNote: 'Rename Note',
    requiresDiarizedTranscription: 'Requires diarized transcription',
    saving: 'Saving...',
    applying: 'Applying...',
    loadingAnalytics: 'Loading analytics...',
    analytics: 'Analytics',
    signedUpUsers: 'Signed-up users',
    activeUsers: 'active users',
    sharedNotes: 'shared notes',
    prompts: 'prompts',
    speakerProfilesLower: 'Speaker profiles',
    workflowCost: 'Workflow cost',
    summaryTokens: 'Summary tokens',
    transcriptionLatency: 'Transcription latency',
    summaryLatency: 'Summary latency',
    generatedNotesByDay: 'Generated notes by day',
    workflowTrends: 'Workflow trends',
    ontologyCoverage: 'Ontology coverage',
    storedAudio: 'Stored audio',
    users: 'Users',
    lastGenerated: 'Last generated',
    lastSeen: 'Last seen',
    notes: 'Notes',
    shared: 'Shared',
    sharedBy: 'Shared By',
    customSpeaker: 'Custom speaker',
    noSpeakerProfilesFound: 'No speaker profiles found.',
    adminAnalyticsForbidden: 'Your Microsoft account is not authorized to view app-wide analytics.',
    chartDataUnavailable: 'Chart data is not available from the deployed admin analytics function yet.',
    ontologyCoverageDescription: 'Speaker profiles with structured ontology data.',
    speakerProfilesMetadataOnly: 'Metadata only. Ontology fields indicate structured speaker context.',
    profileStatusOntology: 'Ontology',
    profileStatusProfile: 'Profile',
    profileStatusEmpty: 'Empty',
    filterTranscriptBySpeaker: 'Filter transcript by speaker',
    allSpeakers: 'All speakers',
    savedSpeakers: 'Saved speakers',
    suggestSpeakersTitle: 'Auto-identify speakers',
    suggestSpeakers: 'Suggest',
    suggestingSpeakers: 'Suggesting…',
    reSuggestSpeakers: 'Re-suggest',
    noSpeakerSuggestions: 'No confident matches — assign manually.',
    unknownSpeakerLabel: 'Unknown',
    applySuggestion: 'Apply',
    lowConfidenceTag: 'low confidence',
    autoUpdatingProfile: 'Updating speaker profile…',
    searchOrTypeSpeaker: 'Search or type a new name...',
    resetSpeakers: 'Reset to “Speaker A/B”',
    issuesNav: 'Issues',
    issuesTitle: 'Feedback & Issues',
    issuesKpiOpen: 'Open',
    issuesKpiTriage: 'Needs triage',
    issuesKpiMine: 'Assigned to me',
    issuesNew: 'New issue',
    issuesFieldTitle: 'Title',
    issuesFieldDesc: 'Description',
    issuesAttach: 'Attach',
    issuesSubmit: 'Submit issue',
    issuesAllAssignees: 'All assignees',
    issuesAllStatus: 'All status',
    issuesSelectHint: 'Select an issue to triage.',
    issuesAssigneeName: 'Assignee name',
    issuesAssignMe: 'Assign to me',
    issuesTriageNote: 'Triage note',
    issuesGenResolution: 'Generate resolution',
    issuesRegenResolution: 'Regenerate resolution',
    issuesRootCauses: 'Root causes',
    issuesChecks: 'Checks',
    issuesFixPlan: 'Fix plan',
    issuesVerification: 'Verification',
    issuesSave: 'Save',
    issuesDelete: 'Delete',
    enterOrSelectSpeaker: 'Enter or select a speaker name.',
    mustSignInLoadSpeakers: 'You must be signed in to load speakers.',
    failedLoadSpeakers: 'Failed to load speakers',
    failedLoadContacts: 'Failed to load Microsoft contacts',
    noProfileYet: 'No profile yet for this speaker.',
    recordAudio: 'Record Audio',
    summarizePrompt: 'Summarize Prompt',
    newProfile: 'New profile',
    updatedProfile: 'Updated profile',
    lookingUpSpeakerData: 'Looking up speaker data...',
    generatingProfilesAi: 'Generating profiles with AI...',
    profilesSaved: 'Profiles saved',
    profilesSavedDescription: 'All profiles were successfully saved to Supabase.',
    failedSaveAllProfiles: 'Failed to save all profiles',
    failedSaveAllProfilesDescription: 'Some profiles could not be saved to Supabase.',
    savingProfiles: 'Saving profiles...',
    confirmSaveAllDescription: 'This will save all unsaved speaker profiles to Supabase.',
    theme: 'Theme',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    openAccountSettings: 'Open account settings',
    loading: 'Loading...',
    switchToDarkMode: 'Switch to dark mode',
    switchToLightMode: 'Switch to light mode',
    loginSubtitle: 'Transcribe audio files and access your Teams chats',
    loginDescription: 'Sign in with your Microsoft account to access your Teams chats and upload audio files for transcription.',
    signInWithMicrosoft: 'Sign in with Microsoft',
    loginConsent: "We'll request access to your Teams chats and profile information.",
    audioTranscription: 'Audio transcription',
    teamsChats: 'Teams chats',
    uploadAudioPageSubtitle: 'Record or upload an audio file to transcribe and summarize',
    clickToStartRecording: 'Click to start recording',
    recordingClickToStop: 'Recording... Click to stop',
    or: 'or',
    dropFilesBrowse: 'Drop files or click to browse',
    largeFilesKeepOpen: 'Large files: keep this tab open and screen on until upload finishes.',
    recordingComplete: 'Recording Complete',
    download: 'Download',
    useRecording: 'Use Recording',
    processing: 'Processing...',
    ready: 'Ready',
    error: 'Error',
    recentRecordingsSubtitle: 'Reuse one of your 10 most recent uploaded or recorded audio files',
    loadingRecentRecordings: 'Loading recent recordings...',
    noRecentRecordings: 'No recent recordings yet.',
    uploaded: 'Uploaded',
    meetingDate: 'Meeting Date',
    addInstructionsOptional: 'Add instructions (optional)',
    addInstructionsPlaceholder: 'e.g., Focus on action items and decisions...',
    tryAgain: 'Try again',
    name: 'Name',
    size: 'Size',
    modified: 'Modified',
    actions: 'Actions',
    rename: 'Rename',
    loadingProject: 'Loading project...',
    projectSubtitle: 'Review project chats and meeting notes in one workspace',
    conversation: 'Conversation',
    chats: 'Chats',
    waitingForReply: 'Waiting for reply...',
    chatMessage: 'Chat message',
    sendMessage: 'Send message',
    noProjectNotes: 'No notes found in this project.',
    mcpSetupTitle: 'Meeting Note MCP setup',
    mcpSetupDescription: 'Connect Meeting Note to ChatGPT or Claude so the assistant can search your notes, summaries, transcripts, projects, and speaker profiles. The MCP is read-only for note data.',
    personalMcpKey: 'Personal MCP key',
    personalMcpKeyDescription: 'Generate a personal key for Claude Desktop. The full key is shown once; after you leave this page only the shortened key label remains.',
    generateKey: 'Generate Key',
    newMcpKeyCopy: 'New MCP key - copy now',
    existingKeys: 'Existing keys',
    loadingKeys: 'Loading keys...',
    noMcpKeys: 'No MCP keys have been generated yet.',
    revoke: 'Revoke',
    chatgptSetup: 'ChatGPT setup',
    chatgptSetupDescription: 'Use this option for ChatGPT web. ChatGPT connects through OAuth, so users sign in with their Microsoft account instead of pasting an API key.',
    chatgptMcpUrl: 'ChatGPT MCP URL',
    claudeDesktopSetup: 'Claude Desktop setup',
    keySafety: 'Key safety',
    quickTestPrompts: 'Quick test prompts',
    mcpReadOnlyNote: 'The MCP can read meeting note data, but it should not edit or delete notes.',
    allRightsReserved: 'All rights reserved.',
  },
  ko: {
    accountSettings: '계정 설정',
    accountSettingsSubtitle: '회의록 작업 공간의 Microsoft 계정 정보',
    account: '계정',
    summaryPrompts: '요약 프롬프트',
    speakerProfiles: '화자 프로필',
    mcpSetup: 'MCP 설정',
    appLanguage: '앱 언어',
    appLanguageDescription: '앱 언어, 전사 표시 언어, 생성되는 요약 언어를 제어합니다.',
    english: '영어',
    korean: '한국어',
    history: '기록',
    meetingNote: '회의록',
    meetingNotes: '회의록',
    historySubtitle: '모든 채팅에서 생성한 회의록',
    filterNotes: '회의록 필터',
    searchNotes: '제목, 요약, 작성자, 화자 또는 태그 검색',
    owner: '소유자',
    allNotes: '전체 회의록',
    myNotes: '내 회의록',
    sharedWithMeNotes: '공유받은 회의록',
    sort: '정렬',
    meetingNewest: '회의일 최신순',
    meetingOldest: '회의일 오래된순',
    createdNewest: '생성일 최신순',
    createdOldest: '생성일 오래된순',
    titleAZ: '제목 A-Z',
    titleZA: '제목 Z-A',
    uploadAudioSubtitle: '오디오를 업로드하거나 녹음한 뒤 회의 요약을 생성합니다.',
    uploadAudioFile: '오디오 파일 업로드',
    uploading: '업로드 중',
    regenerateSummary: '요약 다시 생성',
    forwardSummary: '요약 전달',
    projectNotes: '프로젝트 회의록',
    addToProject: '프로젝트에 추가',
    alreadyInProject: '이미 프로젝트에 있음',
    noProjectsFound: '프로젝트가 없습니다.',
    removeFromProject: '프로젝트에서 제거',
    copied: '복사됨',
    saved: '저장됨',
    sending: '전송 중...',
    sent: '전송됨!',
    delete: '삭제',
    deleteNote: '회의록 삭제',
    deleteProject: '프로젝트 삭제',
    deletePrompt: '프롬프트 삭제',
    deleteSavedSpeaker: '저장된 화자를 삭제할까요?',
    create: '생성',
    createProject: '프로젝트 생성',
    projectName: '프로젝트 이름',
    noteNameRequired: '회의록 이름은 필수입니다.',
    projectNameRequired: '프로젝트 이름은 필수입니다.',
    saveProfile: '프로필 저장',
    editProfile: '프로필 편집',
    profileSaved: '프로필이 저장되었습니다.',
    saveAll: '전체 저장',
    saveAllProfiles: '모든 프로필을 저장할까요?',
    confirmSaveAll: '전체 저장 확인',
    discardSummary: '요약 삭제',
    adminWorkspace: '관리자 작업 공간',
    adminAccessRequired: '관리자 권한 필요',
    transcriptionControls: '전사 설정',
    summaryControls: '요약 설정',
    globalSummaryContext: '전체 요약 컨텍스트',
    settingsSaved: '설정이 저장되었습니다.',
    transcriptionSettingsSaved: '전사 설정이 저장되었습니다.',
    loadingAccount: '계정 정보를 불러오는 중...',
    loadingSpeakerData: '화자 데이터를 불러오는 중...',
    noSavedSpeakerMatched: 'Microsoft 이름과 일치하는 저장된 화자가 없습니다. 전사에서 본인을 라벨링하거나 일치하는 저장 화자를 추가하세요.',
    savedSpeakersDescription: '계정에 저장된 화자 목록입니다. 계정 탭의 Microsoft 이름과 일치하는 프로필은 제외됩니다.',
    useEditProfileHint: '요약 품질을 높이려면 프로필 편집으로 구조화된 화자 컨텍스트를 추가하세요.',
    list: '목록',
    calendar: '캘린더',
    daily: '일간',
    weekly: '주간',
    monthly: '월간',
    summary: '요약',
    transcription: '전사',
    copy: '복사',
    edit: '편집',
    done: '완료',
    save: '저장',
    cancel: '취소',
    editTranscriptSegment: '전사 세그먼트 편집',
    failedSaveSegmentEdit: '전사 세그먼트 편집 저장 실패',
    discard: '삭제',
    uploadAudio: '오디오 업로드',
    recentRecordings: '최근 녹음',
    summarize: '요약 생성',
    project: '프로젝트',
    projects: '프로젝트',
    newProject: '새 프로젝트',
    adminControls: '관리자 설정',
    adminAnalytics: '관리자 분석',
    share: '공유',
    close: '닫기',
    syncProfile: '프로필 동기화',
    renameNote: '회의록 이름 변경',
    requiresDiarizedTranscription: '화자 분리 전사가 필요합니다',
    saving: '저장 중...',
    applying: '적용 중...',
    loadingAnalytics: '분석 데이터를 불러오는 중...',
    analytics: '분석',
    signedUpUsers: '가입 사용자',
    activeUsers: '활성 사용자',
    sharedNotes: '공유된 회의록',
    prompts: '프롬프트',
    speakerProfilesLower: '화자 프로필',
    workflowCost: '워크플로 비용',
    summaryTokens: '요약 토큰',
    transcriptionLatency: '전사 지연 시간',
    summaryLatency: '요약 지연 시간',
    generatedNotesByDay: '일별 생성 회의록',
    workflowTrends: '워크플로 추이',
    ontologyCoverage: '온톨로지 커버리지',
    storedAudio: '저장된 오디오',
    users: '사용자',
    lastGenerated: '마지막 생성',
    lastSeen: '마지막 접속',
    notes: '회의록',
    shared: '공유',
    sharedBy: '공유한 사람',
    customSpeaker: '사용자 지정 화자',
    noSpeakerProfilesFound: '화자 프로필이 없습니다.',
    adminAnalyticsForbidden: '이 Microsoft 계정은 앱 전체 분석을 볼 권한이 없습니다.',
    chartDataUnavailable: '배포된 관리자 분석 함수에서 차트 데이터를 아직 제공하지 않습니다.',
    ontologyCoverageDescription: '구조화된 온톨로지 데이터가 있는 화자 프로필입니다.',
    speakerProfilesMetadataOnly: '메타데이터만 표시합니다. 온톨로지 필드는 구조화된 화자 컨텍스트를 나타냅니다.',
    profileStatusOntology: '온톨로지',
    profileStatusProfile: '프로필',
    profileStatusEmpty: '비어 있음',
    filterTranscriptBySpeaker: '화자별 전사 필터',
    allSpeakers: '모든 화자',
    savedSpeakers: '저장된 화자',
    suggestSpeakersTitle: '화자 자동 식별',
    suggestSpeakers: '제안',
    suggestingSpeakers: '제안 중…',
    reSuggestSpeakers: '다시 제안',
    noSpeakerSuggestions: '확실한 매칭이 없습니다. 직접 지정하세요.',
    unknownSpeakerLabel: '알 수 없음',
    applySuggestion: '적용',
    lowConfidenceTag: '낮은 신뢰도',
    autoUpdatingProfile: '화자 프로필 갱신 중…',
    searchOrTypeSpeaker: '검색하거나 새 이름을 입력...',
    resetSpeakers: 'Speaker A/B로 초기화',
    issuesNav: '이슈',
    issuesTitle: '피드백 & 이슈',
    issuesKpiOpen: 'Open',
    issuesKpiTriage: 'Triage 필요',
    issuesKpiMine: '내가 담당',
    issuesNew: '새 이슈 등록',
    issuesFieldTitle: '제목',
    issuesFieldDesc: '설명',
    issuesAttach: '스크린샷',
    issuesSubmit: '이슈 등록',
    issuesAllAssignees: '전체 담당자',
    issuesAllStatus: '전체 상태',
    issuesSelectHint: '이슈를 선택하면 Triage가 열립니다.',
    issuesAssigneeName: '담당자 이름',
    issuesAssignMe: '나에게 배정',
    issuesTriageNote: 'Triage 노트',
    issuesGenResolution: '해결책 생성',
    issuesRegenResolution: '해결책 재생성',
    issuesRootCauses: '원인 가설',
    issuesChecks: '확인 절차',
    issuesFixPlan: '수정 방향',
    issuesVerification: '검증 방법',
    issuesSave: '저장',
    issuesDelete: '삭제',
    enterOrSelectSpeaker: '화자 이름을 입력하거나 선택하세요.',
    mustSignInLoadSpeakers: '화자를 불러오려면 로그인이 필요합니다.',
    failedLoadSpeakers: '화자를 불러오지 못했습니다',
    failedLoadContacts: 'Microsoft 연락처를 불러오지 못했습니다',
    noProfileYet: '이 화자의 프로필이 아직 없습니다.',
    recordAudio: '오디오 녹음',
    summarizePrompt: '요약 프롬프트',
    newProfile: '새 프로필',
    updatedProfile: '업데이트된 프로필',
    lookingUpSpeakerData: '화자 데이터를 찾는 중...',
    generatingProfilesAi: 'AI로 프로필 생성 중...',
    profilesSaved: '프로필 저장됨',
    profilesSavedDescription: '모든 프로필이 Supabase에 저장되었습니다.',
    failedSaveAllProfiles: '모든 프로필 저장 실패',
    failedSaveAllProfilesDescription: '일부 프로필을 Supabase에 저장하지 못했습니다.',
    savingProfiles: '프로필 저장 중...',
    confirmSaveAllDescription: '저장되지 않은 모든 화자 프로필을 Supabase에 저장합니다.',
    theme: '테마',
    darkMode: '다크 모드',
    lightMode: '라이트 모드',
    openAccountSettings: '계정 설정 열기',
    loading: '불러오는 중...',
    switchToDarkMode: '다크 모드로 전환',
    switchToLightMode: '라이트 모드로 전환',
    loginSubtitle: '오디오 파일을 전사하고 Teams 채팅에 접근하세요',
    loginDescription: 'Microsoft 계정으로 로그인하여 Teams 채팅에 접근하고 오디오 파일을 업로드해 전사하세요.',
    signInWithMicrosoft: 'Microsoft로 로그인',
    loginConsent: 'Teams 채팅 및 프로필 정보 접근 권한을 요청합니다.',
    audioTranscription: '오디오 전사',
    teamsChats: 'Teams 채팅',
    uploadAudioPageSubtitle: '오디오 파일을 녹음하거나 업로드하여 전사하고 요약합니다',
    clickToStartRecording: '클릭하여 녹음 시작',
    recordingClickToStop: '녹음 중... 클릭하여 중지',
    or: '또는',
    dropFilesBrowse: '파일을 끌어오거나 클릭하여 선택',
    largeFilesKeepOpen: '대용량 파일은 업로드가 끝날 때까지 이 탭을 열어 두고 화면을 켜 두세요.',
    recordingComplete: '녹음 완료',
    download: '다운로드',
    useRecording: '녹음 사용',
    processing: '처리 중...',
    ready: '준비됨',
    error: '오류',
    recentRecordingsSubtitle: '최근 업로드 또는 녹음한 오디오 파일 10개 중 하나를 다시 사용하세요',
    loadingRecentRecordings: '최근 녹음을 불러오는 중...',
    noRecentRecordings: '최근 녹음이 아직 없습니다.',
    uploaded: '업로드됨',
    meetingDate: '회의 날짜',
    addInstructionsOptional: '추가 지시사항 (선택)',
    addInstructionsPlaceholder: '예: 실행 항목과 결정 사항에 집중...',
    tryAgain: '다시 시도',
    name: '이름',
    size: '크기',
    modified: '수정됨',
    actions: '작업',
    rename: '이름 변경',
    loadingProject: '프로젝트 불러오는 중...',
    projectSubtitle: '프로젝트 채팅과 회의록을 한 작업 공간에서 확인하세요',
    conversation: '대화',
    chats: '채팅',
    waitingForReply: '응답 대기 중...',
    chatMessage: '채팅 메시지',
    sendMessage: '메시지 보내기',
    noProjectNotes: '이 프로젝트에 회의록이 없습니다.',
    mcpSetupTitle: 'Meeting Note MCP 설정',
    mcpSetupDescription: 'Meeting Note를 ChatGPT 또는 Claude에 연결하여 노트, 요약, 전사, 프로젝트, 화자 프로필을 검색할 수 있게 합니다. MCP는 회의록 데이터를 읽기 전용으로만 사용합니다.',
    personalMcpKey: '개인 MCP 키',
    personalMcpKeyDescription: 'Claude Desktop용 개인 키를 생성합니다. 전체 키는 한 번만 표시되며, 이 페이지를 떠난 뒤에는 축약된 키 라벨만 남습니다.',
    generateKey: '키 생성',
    newMcpKeyCopy: '새 MCP 키 - 지금 복사',
    existingKeys: '기존 키',
    loadingKeys: '키를 불러오는 중...',
    noMcpKeys: '아직 생성된 MCP 키가 없습니다.',
    revoke: '해지',
    chatgptSetup: 'ChatGPT 설정',
    chatgptSetupDescription: 'ChatGPT 웹에서 사용하는 옵션입니다. ChatGPT는 OAuth로 연결되므로 API 키를 붙여넣는 대신 Microsoft 계정으로 로그인합니다.',
    chatgptMcpUrl: 'ChatGPT MCP URL',
    claudeDesktopSetup: 'Claude Desktop 설정',
    keySafety: '키 보안',
    quickTestPrompts: '빠른 테스트 프롬프트',
    mcpReadOnlyNote: 'MCP는 회의록 데이터를 읽을 수 있지만 편집하거나 삭제해서는 안 됩니다.',
    allRightsReserved: '모든 권리 보유.',
  },
} as const;

export type TranslationKey = keyof typeof translations.en;

function readStoredLanguage(): AppLanguage {
  if (typeof window === 'undefined') return 'en';
  const stored = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
  return stored === 'ko' ? 'ko' : 'en';
}

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [appLanguage, setAppLanguageState] = useState<AppLanguage>(() => readStoredLanguage());

  const setAppLanguage = (language: AppLanguage) => {
    setAppLanguageState(language);
  };

  useEffect(() => {
    if (typeof window === 'undefined') return;
    window.localStorage.setItem(LANGUAGE_STORAGE_KEY, appLanguage);
    document.documentElement.lang = appLanguage === 'ko' ? 'ko' : 'en';
  }, [appLanguage]);

  const value = useMemo<LanguageContextValue>(
    () => ({
      appLanguage,
      transcriptLanguage: 'original',
      setAppLanguage,
      t: (key) => translations[appLanguage][key] ?? translations.en[key],
    }),
    [appLanguage]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export function useLanguage(): LanguageContextValue {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
